version: 2
jobs:
  prepare:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-29
    environment:
      JVM_OPTS: -Xmx3g
    steps:
      - checkout
      - restore_cache:
          key: gradle-{{ checksum "build.gradle.kts" }}
      - run:
          name: Download dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle.kts" }}
          destination: reports

  deploy:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-29
    environment:
      JVM_OPTS: -Xmx3g
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle.kts" }}-{{ checksum  "lib/build.gradle.kts" }}
      - run:
          name: Publish to Bintray
          command: ./gradlew test build bintrayUpload -PdryRun=false

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - prepare:
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
      - hold:
          type: approval
          requires:
            - prepare
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
      - deploy:
          requires:
            - hold
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
